### ISSUE TITLE
localhost:9000

### ISSUE THREAD

**Issue by arsen3d** [BasedLabs/NoLabs#91]
Be sure to set
  "hostNetworkingEnabled": true,
C:\Users\arsen\AppData\Roaming\Docker\settings.json

I had to do it manually since I could not get the UI to save the changes.
<img width="690" alt="image" src="https://github.com/user-attachments/assets/5a67e664-7e08-4b01-b55e-7f553066cf2e">

I wonder if it would be better if networking was setup internal to docker with port 9000 exposed.
Nginx might be useful too.

**Comment by JaktensTid** [comment]
Hi @arsen3d . Just for clarification - is everything OK with UI, were you able to save the data?
We are working on the beta version of our app, where there would not be vue server running in docker container. Frontend will be bundled and served by fastapi (which is a correct way of doing it, serving fastapi + vue server was an architectural mistake). So there would not be any problems with ports

**Comment by arsen3d** [comment]
> is everything OK with UI, were you able to save the data?

Yes. I managed to get everything working on that version. There is a new re-architected version out now, which I have not tried.
